info:
  version: 1.0.0
  title: go chat
  contact: {}
paths:
  /index:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - 首页
  /user/create:
    get:
      parameters:
      - description: 用户名
        in: query
        name: name
        type: string
      - description: 密码
        in: query
        name: pwd
        type: string
      - description: 重复密码
        in: query
        name: repwd
        type: string
      responses:
        "200":
          description: code","message"}
          schema:
            type: string
      summary: 新增用户
      tags:
      - 用户模块
  /user/list:
    get:
      responses:
        "200":
          description: code","userList"}
          schema:
            type: string
      summary: 用户列表
      tags:
      - 用户模块
swagger: "2.0"
